WebApplication27/Models/REGION.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION
    {
        public REGION()
        {
            this.DEPARTMENTS = new HashSet<DEPARTMENT>();
        }
    
        public decimal REGION_ID { get; set; }
        public string REGION_NAME { get; set; }
        public string VISIBILITY_STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_DATE { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual ICollection<DEPARTMENT> DEPARTMENTS { get; set; }
    }
}

WebApplication27/Controllers/RegionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication27.Models;
using PagedList;
using WebApplication27.Models.Infrastructure;

namespace WebApplication27.Controllers
{
    [CustomAuthenticationFilter]
    [CustomAuthorize("Manage Regions")]
    public class RegionsController : Controller
    {
        // GET: Regions
        private DB_Model db = new DB_Model();

        [HttpGet]
        public ActionResult Index(int? page, string name, string Filter_Value)
        {

                const int pagesize = 5;//number of items per each page
                int pagenum = (page ?? 1); //defult page
                if (name != null)
                {
                    page = 1;
                }
                else
                {

                    name = Filter_Value;// to filter the list by name across all pages ... not only the first page

                }
                ViewBag.FilterValue = name;

                List<REGION> data = db.REGIONS.OrderBy(q => q.REGION_NAME).ToList();//list to all regions ordered by their names

            if (!String.IsNullOrEmpty(name) && name.Length <= 150)
            {
                     data = data.Where(m => m.REGION_NAME.ToLower().Contains(name.ToLower())).ToList();//filter by the name
            }

                return View(data.ToPagedList(pagenum, pagesize));
        }

        public ActionResult Create()
        {

            return View();
        }
   
        [HttpPost]
        public ActionResult Save(RegionModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    REGION data = new REGION();
                    //insert new region
                    data.REGION_NAME = model.REGION_NAME;
                    data.VISIBILITY_STATUS = model.Vsibility_status;
                    data.CREATED_DATE = DateTime.Now;
                    data.CREATED_BY = Convert.ToDecimal(User.Identity.Name);
                    db.REGIONS.Add(data);
                    db.SaveChanges();
                    TempData["Success"] = data.REGION_NAME + " has been saved successfully";//display a message to inform that (The region is added successfully)
                    return RedirectToAction("Index");

                }
                else
                {

                    return View("Create", model); //if model is not valid //display all validation message

                }
            }
            catch (Exception ex) when (ex.InnerException.InnerException.Message.Contains("ORA-00001"))
            {

                TempData["Danger"] = "Region is already exists";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["Danger"] = "Sorry, something went wrong";
                return RedirectToAction("Index");

            }

        }
 
        [HttpGet]
        public ActionResult GetID2(int id)
        {

            REGION model = db.REGIONS.Where(Models => Models.REGION_ID == id).FirstOrDefault();  

            if (model != null)
            {
                string check = CheckRegionId(id);

                switch (check)
                {
                    case "Used":

                        return View("EditUsed", _getRegion(id));

                    case "Unused":

                        return View("Edit", _getRegion(id));

                    default:

                        return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index", "Error");




        }

        [HttpPost]
        public ActionResult edit(RegionModel model)
        {
            try
            {
                REGION data = db.REGIONS.Where(Models => Models.REGION_ID == model.REGION_ID).FirstOrDefault();

                if (ModelState.IsValid)
                {
                    if (model != null)
                    {
                        //update
                        data.REGION_NAME = model.REGION_NAME;
                        data.VISIBILITY_STATUS = model.Vsibility_status;
                        data.CHANGED_DATE = DateTime.Now;
                        data.CREATED_BY = Convert.ToDecimal(User.Identity.Name);
                        db.SaveChanges();
                        TempData["Success"] = "The changes are saved successfully"; //display a message to inform that  (changes are saved successfully)

                        return RedirectToAction("Index");

                    }
                    return RedirectToAction("Index", "Error");


                }
                else
                {
                    return View("Edit", model);  //if model is not valid, return the view with all validation message


                }
            }
            catch (Exception ex) when (ex.InnerException.InnerException.Message.Contains("ORA-00001"))
            {
                TempData["Danger"] = "Region is already exists";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                 TempData["Danger"] = "Sorry, something went wrong";
                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        public ActionResult editUsed(RegionModel model)
        {
            try
            {
                REGION data = db.REGIONS.Where(Models => Models.REGION_ID == model.REGION_ID).FirstOrDefault();///get all related data to the current region Id  


                if (ModelState.IsValid)
                {
                    if (data != null)
                    {
                        //update status
                        data.VISIBILITY_STATUS = model.Vsibility_status;
                        data.CHANGED_DATE = DateTime.Now;
                        data.CREATED_BY = Convert.ToDecimal(User.Identity.Name);
                        db.SaveChanges();
                        TempData["Success"] = "The changes are saved successfully"; //display a message to inform that (changes are saved successfully)

                        return RedirectToAction("Index");
                    }
                    return RedirectToAction("Index", "Error");

                }
                else
                {
                    //if model is not valid 
                    //we return the view with all validation messages
                    return View("Edit", model);
                }
            }
            catch (Exception)
            {
                TempData["Danger"] = "Sorry, something went wrong";
                return RedirectToAction("Index");

            }
        }

        [HttpGet]
        public ActionResult GetID3(int id)
        {

            REGION model = db.REGIONS.Where(Models => Models.REGION_ID == id).SingleOrDefault();//get all related data to the current region Id  

            if (model != null && CheckRegionId(id) == "Unused")
            {
                return PartialView(model);
            }

            //not allowed to delete
            return PartialView("DeleteUsed");


        }

        [HttpPost]
        public ActionResult deleteRegion(RegionModel model)
        {
            try
            {
                //get current region Id --> to delete it
                REGION data = db.REGIONS.Where(Models => Models.REGION_ID == model.REGION_ID).FirstOrDefault();

                if (data != null)
                {
                    db.REGIONS.Remove(data);//delete
                    db.SaveChanges();
                    TempData["Success"] = "Region deleted successfully"; //display a message to inform that (The region is deleted successfully)
                    return RedirectToAction("Index");

                }

                return RedirectToAction("Index");
            }
            catch (Exception ex) when (ex.InnerException.InnerException.Message.Contains("ORA-02292"))
            {
                TempData["Danger"] = "You cannot delete this region, since it has been used before";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["Danger"] = "Sorry, something went wrong";
                return RedirectToAction("Index");

            }
        }


        public string CheckRegionId(decimal id)
        {

            var check = db.DEPARTMENTS.Where(x => x.REGION_ID == id).FirstOrDefault();

            string status;

            if (check != null)
            {

                status = "Used";
            }
            else
            {

                status = "Unused";
            }

            return status;

        }

        private RegionModel _getRegion(int id)
        {

                REGION model = db.REGIONS.Where(Models => Models.REGION_ID == id).SingleOrDefault();  //get all related data to the current region Id  

                RegionModel RegionModel = new RegionModel();
                RegionModel.REGION_ID = model.REGION_ID;
                RegionModel.REGION_NAME = model.REGION_NAME;
                RegionModel.Vsibility_status = model.VISIBILITY_STATUS;
                return RegionModel;

        }


    }
}

WebApplication27/Views/Regions/Create.cshtml
@{
    ViewBag.Title = "Create";
}

@model WebApplication27.Models.RegionModel

<div class="d-flex justify-content-center" style="margin:5rem; ">

    <div class="card w-75">
        <div class="card-body">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Add Region</legend>
                <form method="post" action="@Url.Action("Save", "Regions")">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <label>Region Name</label><span class="text-danger">  *</span><br />
                        @Html.TextBoxFor(Models => Models.REGION_NAME, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.REGION_NAME, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Status</label><span class="text-danger">  *</span><br />
                        @Html.RadioButtonFor(Models => Models.Vsibility_status, "Visible", new { required = "required", name = "Status" }) Visible<br />
                        @Html.RadioButtonFor(Models => Models.Vsibility_status, "Hide", new { required = "required", name = "Status" }) Hide
                        @Html.ValidationMessageFor(m => m.Vsibility_status, "", new { @class = "text-danger" })
                    </div>


                    <button type="submit" style="background-color: #428bca; color: #fff" class="btn">Save </button>


                </form>
            </fieldset>
        </div>
    </div>
</div>

WebApplication27/Views/Regions/DeleteUsed.cshtml
<div>


    <div class="form-horizontal">

        <div class="form-group">

            <div class="col-md-10">
                <p>You cannot delete this region since it has been used before</p>

            </div>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

        </div>
    </div>




</div>

WebApplication27/Views/Regions/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

@model WebApplication27.Models.RegionModel

<div class="d-flex justify-content-center" style="margin:5rem; ">

    <div class="card w-75">
        <div class="card-body">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Edit Region</legend>
                <form method="post" action="@Url.Action("edit", "Regions")">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.REGION_ID)
                    <div class="form-group">
                        <label>Region Name</label><span class="text-danger">  *</span><br />
                        @Html.TextBoxFor(Models => Models.REGION_NAME, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.REGION_NAME, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label>Status</label><span class="text-danger">  *</span><br />
                        @Html.RadioButtonFor(Models => Models.Vsibility_status, "Visible", new { required = "required", name = "Status" }) Visible<br />
                        @Html.RadioButtonFor(Models => Models.Vsibility_status, "Hide", new { required = "required", name = "Status" }) Hide
                        @Html.ValidationMessageFor(m => m.Vsibility_status, "", new { @class = "text-danger" })
                    </div>

                    <button type="submit" style="background-color: #428bca; color: #fff" class="btn">Save </button>


                </form>
            </fieldset>
        </div>
    </div>
</div>

WebApplication27/Views/Regions/EditUsed.cshtml
@{
    ViewBag.Title = "Edit";
}

@model WebApplication27.Models.RegionModel

<div class="d-flex justify-content-center" style="margin:5rem; ">

    <div class="card w-75">
        <div class="card-body">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Edit Region</legend>
                <form method="post" action="@Url.Action("editUsed", "Regions")">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.REGION_ID)
                    <div class="form-group">
                        <label>Region Name</label><br />
                        @Html.DisplayFor(Models => Models.REGION_NAME, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.REGION_NAME, "", new { @class = "text-danger" })
                        @Html.HiddenFor(Models => Models.REGION_NAME)

                    </div>

                    <div class="form-group">
                        <label>Status</label><span class="text-danger">  *</span><br />
                        @Html.RadioButtonFor(Models => Models.Vsibility_status, "Visible", new { required = "required", name = "Status" }) Visible<br />
                        @Html.RadioButtonFor(Models => Models.Vsibility_status, "Hide", new { required = "required", name = "Status" }) Hide
                        @Html.ValidationMessageFor(m => m.Vsibility_status, "", new { @class = "text-danger" })
                    </div>

                    <button type="submit" style="background-color: #428bca; color: #fff" class="btn">Save </button>


                </form>
            </fieldset>
        </div>
    </div>
</div>

WebApplication27/Views/Regions/GetID3.cshtml
@model WebApplication27.Models.REGION

<div>

    @using (Html.BeginForm("deleteRegion", "Regions", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.REGION_ID)

        <div class="form-horizontal">

            <div class="form-group">

                <div class="col-md-10">
                    <p>Are you sure you want to delete @Html.DisplayFor(Model => Model.REGION_NAME) region</p>

                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger" value="Delete">Delete</button>

            </div>
        </div>

    }


</div>

WebApplication27/Views/Regions/Index.cshtml
@{
    ViewBag.Title = "Regions";
}


@using PagedList.Mvc

@model PagedList.IPagedList<WebApplication27.Models.REGION>

<h4 style="margin-bottom:20px; margin-top:30px">Regions</h4>



@*alert messages*@

@if (TempData["Danger"] != null)
{
    <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @TempData["Danger"]
    </div>
}


@if (TempData["Success"] != null)
{
    <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Success!</strong> @TempData["Success"]
    </div>

}

@*Search Form*@
@using (Html.BeginForm("Index", "Regions", FormMethod.Get))
{
    <div class="row">
        <div class="col-10">
            <div class="input-group mb-3 w-25">
                @Html.TextBox("name", ViewBag.FilterValue as string, new { @class = "form-control", placeholder = "Name", })

                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Search</button>
                </div>
            </div>
        </div>
        <div class="col-2">
            <a href="@Url.Action("create", "Regions")" class="btn" style=" background-color: #428bca; color: #fff;">+ Add Region</a>
        </div>
    </div>


}


@*table to read all regions *@
<table class="table">
    <thead>
        <tr>
            <th>Region Name</th>
            <th>Status</th>


            <th>Actions</th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {

        <tr id="@item.REGION_ID">
            <td>

                @Html.DisplayFor(modelItem => item.REGION_NAME)
            </td>
            <td>

                @Html.DisplayFor(modelItem => item.VISIBILITY_STATUS)
            </td>


            <td>



                <a class="btn btn-link" href="@Url.Action("GetID2", "Regions", new { id = item.REGION_ID })">
                    Edit
                </a>  |
                <input class="vh btn btn-link" type="button" value="Delete"
                       data-assigned-id="@item.REGION_ID" data-toggle="modal" data-target="#exampleModalLong1" />


            </td>


        </tr>



    }


</table>
@*pagination*@

<p>
    @Html.PagedListPager(Model, page => Url.Action("Index", "Regions",
new
{
    page,
    Filter_Value = ViewBag.FilterValue
}))
</p>

@*model for delete regions*@
<div class="modal fade" id="exampleModalLong1" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Delete Region</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="partial11">
                <div class="modal-body">
                </div>
            </div>

        </div>
    </div>
</div>

<script type="text/javascript">
            $(function () {
                $('.vh').click(function () {
                    var id = $(this).data('assigned-id');
                    var route = '@Url.Action("GetID3", "Regions")?id=' + id;
                $('#partial11').load(route);
            });

        });

</script>