WebApplication27/Models/MULTIPLE_CHOICE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTIPLE_CHOICE
    {
        public MULTIPLE_CHOICE()
        {
            this.CASE_QUESTIONS = new HashSet<CASE_QUESTIONS>();
        }
    
        public decimal CHOICE_ID { get; set; }
        public string CHOICE_NAM { get; set; }
        public decimal QUESTION_ID { get; set; }
        public Nullable<decimal> DISPLAY_ORDER { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_DATE { get; set; }
        public string VISIBILITY_STATUS { get; set; }
    
        public virtual ICollection<CASE_QUESTIONS> CASE_QUESTIONS { get; set; }
        public virtual USER USER { get; set; }
        public virtual QUESTION QUESTION { get; set; }
    }
}

WebApplication27/Controllers/MultipleChoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApplication27.Models;
using PagedList;
using System.Web.Mvc;
using WebApplication27.Models.Infrastructure;

namespace WebApplication27.Controllers
{
    [CustomAuthenticationFilter]
    [CustomAuthorize("Manage Choices")]

    public class MultipleChoiceController : Controller
    {
        private DB_Model db = new DB_Model();

        // GET: MultipleChoice

        public ActionResult Index(int? page, string name, string Filter_Value)
        {

                const int pagesize = 5;//number of items per each page
                int pagenum = (page ?? 1); //defult page
                if (name != null)
                {
                    page = 1;
                }
                else
                {

                    name = Filter_Value;// to filter the list  by name across all page

                }
                ViewBag.FilterValue = name;

                List<MULTIPLE_CHOICE> data = db.MULTIPLE_CHOICE.OrderBy(q => q.QUESTION.QUESTION1).ThenBy(X=>X.CHOICE_NAM).ToList();

                if (!String.IsNullOrEmpty(name) && name.Length <= 150)
                {
                     data = data.Where(m => m.CHOICE_NAM.ToLower().Contains(name.ToLower())).OrderBy(x => x.CHOICE_NAM).ToList();//filter by the choice name ... ordred by name

                }
    
                    return View(data.ToPagedList(pagenum, pagesize)); //list to all choice ordered by their names


        }

        public ActionResult create()
        {

            List<QUESTION> list = db.QUESTIONS.Where(m => m.ANSWER_TYPE == "Multiple Choice").Where(x=>x.VISIBILITY_STATUS == "Visible").OrderBy(x=>x.QUESTION1).ToList();
            ViewBag.question = new SelectList(list, "QUESTION_ID", "QUESTION1");  //list all visible questions that have an answer type (Multiple Choice)     
            return View("Create");

            
        }
    
        public ActionResult Save(choiceModel model)
        {
            try
            {


                if (ModelState.IsValid)
                {
                    MULTIPLE_CHOICE ch = new MULTIPLE_CHOICE();
                    ch.CHOICE_NAM = model.CHOICE_NAM;
                    ch.QUESTION_ID = model.QUESTION_ID;
                    ch.DISPLAY_ORDER = model.DISPLAY_ORDER;
                    ch.VISIBILITY_STATUS = model.VISIBILITY_STATUS;
                    ch.CREATED_DATE = DateTime.Now;
                    ch.CREATED_BY = Convert.ToDecimal(User.Identity.Name);
                    db.MULTIPLE_CHOICE.Add(ch); //insert new choice
                    db.SaveChanges();
                    TempData["Success"] =  ch.CHOICE_NAM+ " has been saved successfully";
                    return RedirectToAction("Index"); //display a message to inform that (The choice is added successfully)

                }
                else
                {

                    List<QUESTION> list = db.QUESTIONS.Where(m => m.ANSWER_TYPE == "Multiple Choice").Where(x => x.VISIBILITY_STATUS == "Visible").OrderBy(x => x.QUESTION1).ToList();
                    ViewBag.question = new SelectList(list, "QUESTION_ID", "QUESTION1");
                    return View("Create", model); //if model is not valid  //we return the view with all validation message and question list

                }
            }
            catch (Exception ex)when (ex.InnerException.InnerException.Message.Contains("ORA-00001"))
                {
                    TempData["Danger"] = "Choice is already exists";
                    return RedirectToAction("Index");
                }
            catch (Exception)
            {
                    TempData["Danger"] = "Sorry, something went wrong";
                    return RedirectToAction("Index");
            }


        }

        public ActionResult GetID2(int id)
        {

              MULTIPLE_CHOICE model = db.MULTIPLE_CHOICE.Where(Models => Models.CHOICE_ID == id).SingleOrDefault();

              List<QUESTION> list = db.QUESTIONS.Where(m => m.ANSWER_TYPE == "Multiple Choice").ToList();
              ViewBag.question = new SelectList(list, "QUESTION_ID", "QUESTION1"); //list all visible questions that have an answer type (Multiple Choice)        

                if (model != null && CheckId(id) == "Unused")
                {
                    return View("Edit", _getChoice(id));

                }
                if (model != null && CheckId(id) == "Used")
                {
                return View("EditUsed", _getChoice(id));

                }



            TempData["Danger"] = "You cannot edit this choice, since it has been used before";
            return RedirectToAction("Index");

                

        }
     
        public ActionResult edit(choiceModel model)
        {
            try
            {

                MULTIPLE_CHOICE data = db.MULTIPLE_CHOICE.FirstOrDefault(Models => Models.CHOICE_ID == model.CHOICE_ID);

                if (ModelState.IsValid)
                {
                   
                    if (data != null && CheckId(model.CHOICE_ID) == "Unused")
                    {
                        //update
                        data.QUESTION_ID = model.QUESTION_ID;
                        data.CHOICE_NAM = model.CHOICE_NAM;
                        data.DISPLAY_ORDER = model.DISPLAY_ORDER;
                        data.VISIBILITY_STATUS = model.VISIBILITY_STATUS;
                        data.CHANGED_DATE = DateTime.Now;
                        data.CREATED_BY = Convert.ToDecimal(User.Identity.Name);

                        TempData["Success"] = "The changes are saved successfully";//display a message to inform that  (changes are saved successfully)

                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    if (data != null && CheckId(model.CHOICE_ID) == "Used")
                    {
                        //update status only
                        data.VISIBILITY_STATUS = model.VISIBILITY_STATUS;
                        data.CHANGED_DATE = DateTime.Now;
                        data.CREATED_BY = Convert.ToDecimal(User.Identity.Name);

                        TempData["Success"] = "The changes are saved successfully";//display a message to inform that  (changes are saved successfully)

                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                }
                else 
                { 

                    List<QUESTION> list = db.QUESTIONS.Where(m => m.ANSWER_TYPE == "Multiple Choice").Where(x => x.VISIBILITY_STATUS == "Visible").OrderBy(x => x.QUESTION1).ToList();
                    ViewBag.question = new SelectList(list, "QUESTION_ID", "QUESTION1");
                    return View("Edit", model);   //if model is not valid  //we return the page with all validation message and question list

                }
            }
            catch (Exception ex) when (ex.InnerException.InnerException.Message.Contains("ORA-00001"))
            {
                TempData["Danger"] = "Choice already exist";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["Danger"] = "Sorry, something went wrong";
                return RedirectToAction("Index");

            }

            }

        public ActionResult GetID3(int CHOICE_ID)

        {
            MULTIPLE_CHOICE model = db.MULTIPLE_CHOICE.FirstOrDefault(Models => Models.CHOICE_ID == CHOICE_ID);

            if (model != null && CheckId(model.CHOICE_ID) == "Unused")
            {

                return PartialView(_getChoice(CHOICE_ID));


            }
            return PartialView("DeleteUsed");//not allowed to delete


        }

        public ActionResult Delete(int CHOICE_ID)
        {
            try
            {
                MULTIPLE_CHOICE model = db.MULTIPLE_CHOICE.FirstOrDefault(Models => Models.CHOICE_ID == CHOICE_ID);



                if (model != null && CheckId(model.QUESTION_ID) == "Unused")
                {
                    db.MULTIPLE_CHOICE.Remove(model);//delete the choice
                    db.SaveChanges();
                    TempData["Success"] = "Choice deleted successfully"; //display a message to inform that (The choice is deleted successfully)
                    return RedirectToAction("Index");
                }

                TempData["Danger"] = "You cannot delete this choice, since it has been used before";
                return RedirectToAction("Index");

                
            }
            catch (Exception ex) when (ex.InnerException.InnerException.Message.Contains("ORA-02292"))
            {
                TempData["Danger"] = "You cannot delete this choice, since it has been used before";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["Danger"] = "Sorry, something went wrong";
                return RedirectToAction("Index");

            }


        }

        private choiceModel _getChoice(int id)
        {

            MULTIPLE_CHOICE model = db.MULTIPLE_CHOICE.Where(Models => Models.CHOICE_ID == id).SingleOrDefault();

            choiceModel c = new choiceModel();
            c.CHOICE_ID = model.CHOICE_ID;
            c.QUESTION_ID = model.QUESTION_ID;
            c.CHOICE_NAM = model.CHOICE_NAM;
            c.VISIBILITY_STATUS = model.VISIBILITY_STATUS;
            c.DISPLAY_ORDER = model.DISPLAY_ORDER;
            return c;

        }

        private string CheckId(decimal id)
        {
            var check = db.CASE_QUESTIONS.Where(x => x.CHOICE_ID == id).FirstOrDefault();

            string status;

            if (check != null)
            {

WebApplication27/Views/MultipleChoice/Create.cshtml
@{
    ViewBag.Title = "Create";
}
@model WebApplication27.Models.choiceModel

<div class="d-flex justify-content-center" style="margin:5rem; ">

    <div class="card w-75">
        <div class="card-body">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Add Choice</legend>
                <form method="post" action="@Url.Action("Save", "MultipleChoice")">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <lable>Referenced Question</lable><span class="text-danger">  *</span><br />
                        @Html.DropDownListFor(Models => Models.QUESTION_ID, ViewBag.question as SelectList, "Select", new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.QUESTION_ID, "", new { @class = "text-danger" })

                    </div>
                    <div class="form-group">
                        <lable>Choice Name</lable><span class="text-danger">  *</span><br />
                        @Html.TextBoxFor(Models => Models.CHOICE_NAM, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.CHOICE_NAM, "", new { @class = "text-danger" })

                    </div>
                    <div class="form-group">
                        <lable>Display Order</lable><span class="text-danger">  *</span><br />
                        @Html.TextBoxFor(Models => Models.DISPLAY_ORDER, new { @class = "form-control", required = "required", onkeypress = "return validateNumber(event)" })
                        @Html.ValidationMessageFor(m => m.DISPLAY_ORDER, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">

                        <label>Status</label><span class="text-danger">  *</span><br />
                        @Html.RadioButtonFor(Models => Models.VISIBILITY_STATUS, "Visible", new { name = "Status", required = "required", }) Visible<br />
                        @Html.RadioButtonFor(Models => Models.VISIBILITY_STATUS, "Hide", new { name = "Status" }) Hide
                        @Html.ValidationMessageFor(m => m.VISIBILITY_STATUS, "", new { @class = "text-danger" })

                    </div>
                    <button type="submit" style="background-color: #428bca; color: #fff" class="btn">Save </button>


                </form>
            </fieldset>
        </div>
    </div>
</div>

WebApplication27/Views/MultipleChoice/DeleteUsed.cshtml
<div>


    <div class="form-horizontal">

        <div class="form-group">

            <div class="col-md-10">
                <p>You cannot delete this choice since it has been used before</p>

            </div>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

        </div>
    </div>




</div>

WebApplication27/Views/MultipleChoice/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

@model WebApplication27.Models.choiceModel
<div class="d-flex justify-content-center" style="margin:5rem; ">

    <div class="card w-75">
        <div class="card-body">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Edit Choice</legend>
                <form method="post" action="@Url.Action("edit", "MultipleChoice")">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.CHOICE_ID)
                    @Html.ValidationMessageFor(m => m.CHOICE_ID, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <lable>Referenced Question</lable><span class="text-danger">  *</span><br />
                        @Html.DropDownListFor(Models => Models.QUESTION_ID, ViewBag.question as SelectList, "Select", new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.QUESTION_ID, "", new { @class = "text-danger" })

                    </div>
                    <div class="form-group">
                        <lable>Choice Name</lable><span class="text-danger">  *</span><br />
                        @Html.TextBoxFor(Models => Models.CHOICE_NAM, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.CHOICE_NAM, "", new { @class = "text-danger" })

                    </div>
                    <div class="form-group">
                        <lable>Display Order</lable><span class="text-danger">  *</span><br />
                        @Html.TextBoxFor(Models => Models.DISPLAY_ORDER, new { @class = "form-control", required = "required", onkeypress = "return validateNumber(event)" })
                        @Html.ValidationMessageFor(m => m.DISPLAY_ORDER, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">

                        <label>Status</label><span class="text-danger">  *</span><br />
                        @Html.RadioButtonFor(Models => Models.VISIBILITY_STATUS, "Visible", new { name = "Status", required = "required", }) Visible<br />
                        @Html.RadioButtonFor(Models => Models.VISIBILITY_STATUS, "Hide", new { name = "Status" }) Hide
                        @Html.ValidationMessageFor(m => m.VISIBILITY_STATUS, "", new { @class = "text-danger" })

                    </div>

                    <button type="submit" style="background-color: #428bca; color: #fff" class="btn">Save Changes</button>


                </form>
            </fieldset>
        </div>
    </div>
</div>

WebApplication27/Views/MultipleChoice/EditUsed.cshtml
@{
    ViewBag.Title = "Edit";
}

@model WebApplication27.Models.choiceModel
<div class="d-flex justify-content-center" style="margin:5rem; ">

    <div class="card w-75">
        <div class="card-body">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Edit Choice</legend>
                <form method="post" action="@Url.Action("edit", "MultipleChoice")">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.CHOICE_ID)
                    @Html.ValidationMessageFor(m => m.CHOICE_ID, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <lable>Referenced Question</lable><br />
                        @Html.DisplayFor(Models => Models.QUESTION.QUESTION1)
                        @Html.ValidationMessageFor(m => m.QUESTION_ID, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.QUESTION_ID)


                    </div>
                    <div class="form-group">
                        <lable>Choice Name </lable><br />
                        @Html.DisplayFor(Models => Models.CHOICE_NAM, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.CHOICE_NAM, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.CHOICE_NAM)

                    </div>
                    <div class="form-group">
                        <lable>Display Order</lable><br />
                        @Html.DisplayFor(Models => Models.DISPLAY_ORDER, new { @class = "form-control", required = "required", onkeypress = "return validateNumber(event)" })
                        @Html.ValidationMessageFor(m => m.DISPLAY_ORDER, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.DISPLAY_ORDER)

                    </div>
                    <div class="form-group">

                        <label>Status</label><span class="text-danger">  *</span><br />
                        @Html.RadioButtonFor(Models => Models.VISIBILITY_STATUS, "Visible", new { name = "Status", required = "required", }) Visible<br />
                        @Html.RadioButtonFor(Models => Models.VISIBILITY_STATUS, "Hide", new { name = "Status" }) Hide
                        @Html.ValidationMessageFor(m => m.VISIBILITY_STATUS, "", new { @class = "text-danger" })

                    </div>

                    <button type="submit" style="background-color: #428bca; color: #fff" class="btn">Save Changes </button>


                </form>
            </fieldset>
        </div>
    </div>
</div>

WebApplication27/Views/MultipleChoice/GetID2.cshtml
@model WebApplication27.Models.choiceModel

<div>

    @using (Html.BeginForm("edit", "MultipleChoice", FormMethod.Post))
    {@Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.CHOICE_ID)
                                    <div class="form-horizontal">

                                        <div class="form-group">
                                            <lable>Choice Name</lable><span class="text-danger">  *</span><br />
                                            @Html.TextBoxFor(Models => Models.CHOICE_NAM, new { @class = "form-control", required = "required" })
                                        </div>
                                        <div class="form-group">
                                            <lable>Referenced Question</lable><span class="text-danger">  *</span><br />
                                            @Html.DropDownListFor(Models => Models.QUESTION_ID, ViewBag.question as SelectList, "Select", new { @class = "form-control", required = "required" })
                                        </div>
                                        <div class="form-group">
                                            <lable>Display Order</lable><span class="text-danger">  *</span><br />
                                            @Html.TextBoxFor(Models => Models.DISPLAY_ORDER, new { @class = "form-control", required = "required", onkeypress = "return validateNumber(event)" })


                                        </div>

                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" style="background-color: #428bca; color: #fff" class="btn">Save changes</button>
                                        </div>
                                    </div>}
</div>
<script type="text/javascript">

        function validateNumber(e) {
            const pattern = /^[0-9]$/;

            return pattern.test(e.key)
        }
</script>

WebApplication27/Views/MultipleChoice/GetID3.cshtml
@model WebApplication27.Models.choiceModel

<div>

    @using (Html.BeginForm("Delete", "MultipleChoice", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.CHOICE_ID)
        <div class="form-horizontal">
            <form method="post">
                <div class="form-group">

                    <div class="col-md-10">
                        <h6>Are you sure you want to delete @Html.DisplayFor(model => model.CHOICE_NAM) choice</h6>


                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger" value="Delete">Delete</button>
                </div>

            </form>
        </div>
    }


</div>

WebApplication27/Views/MultipleChoice/Index.cshtml
@{
    ViewBag.Title = "Choices";
}

@using PagedList.Mvc

@model PagedList.IPagedList<WebApplication27.Models.MULTIPLE_CHOICE>

<h4 style="margin-bottom:20px; margin-top:30px">Choices</h4>


@*alert messages*@
@if (TempData["Danger"] != null)
{
    <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @TempData["Danger"]
    </div>
}

@if (TempData["Success"] != null)
{
    <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Success!</strong> @TempData["Success"]
    </div>

}

@if (TempData["choice"] != null)
{
    <div class="success-message">
        <div class="modal fade" id="Model" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">


                <div class="modal-content">
                    <div class="modal-header">
                        <h4>Message</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>  You cannot edit this choice since it has been used before</p>
                    </div>
                </div>

            </div>
        </div>
    </div>

}


@*Search Form*@
@using (Html.BeginForm("Index", "MultipleChoice", FormMethod.Get))
{
    <div class="row">
        <div class="col-10">
            <div class="input-group mb-3 w-25">
                @Html.TextBox("name", ViewBag.FilterValue as string, new { @class = "form-control", placeholder = "Name", })

                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Search</button>
                </div>
            </div>
        </div>
        <div class="col-2">
            <a href="@Url.Action("Create", "MultipleChoice")" class="btn" style="background-color: #428bca;color: #fff;">+ Add Choice</a>
        </div>
    </div>
   
}

@*model for delete choice*@
<div class="modal fade" id="exampleModalLong1" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Delete Choice</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="partial11">



                </div>
            </div>

        </div>
    </div>
</div>


@*Table To read  all choice*@

<table class="table m-1">
    <thead>
        <tr>

            <th>Choice Name</th>
            <th>Question </th>
            <th>Display Order</th>
            <th>Status</th>

            <th>Actions</th>
        </tr>
    </thead>



    @foreach (var item in Model)
    {

<tr id="@item.CHOICE_ID">
    <td>
        @Html.DisplayFor(modelItem => item.CHOICE_NAM)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.QUESTION.QUESTION1)
    </td>
    <td>
        @{

            var s = item.DISPLAY_ORDER.ToString();

            @Html.DisplayFor(x => s)


        }
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.VISIBILITY_STATUS)
    </td>
    <td>



        <a class="btn btn-link" href="@Url.Action("GetID2", "MultipleChoice", new { id = item.CHOICE_ID })">
            Edit
        </a>  |
        <input class="vh btn btn-link" type="button" value="Delete"
               data-assigned-id="@item.CHOICE_ID" data-toggle="modal" data-target="#exampleModalLong1" />



    </td>


</tr>



    }


</table>


@*pagination*@

<p>
    @Html.PagedListPager(Model, page => Url.Action("Index", "MultipleChoice",
new
{
    page,
    Filter_Value = ViewBag.FilterValue
}))
</p>
<script type="text/javascript">
    $(document).ready(function () {
        $("#Model").modal();
    });
    $(function () {
        $('.vh').click(function () {
           var CHOICE_ID = $(this).data('assigned-id');
           var route = '@Url.Action("GetID3", "MultipleChoice")?CHOICE_ID=' + CHOICE_ID;
                $('#partial11').load(route);
            });

        });

</script>