WebApplication27/Models/REFERENCE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERENCE
    {
        public REFERENCE()
        {
            this.CASE_REFERENCES = new HashSet<CASE_REFERENCES>();
        }
    
        public decimal REFERENCE_ID { get; set; }
        public string REFERENCE_NAME { get; set; }
        public string VISIBILIT_STATUS { get; set; }
        public Nullable<decimal> DISPLAY_ORDER { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CHANGED_DATE { get; set; }
    
        public virtual ICollection<CASE_REFERENCES> CASE_REFERENCES { get; set; }
        public virtual USER USER { get; set; }
    }
}

WebApplication27/Controllers/ReferencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApplication27.Models;
using PagedList;
using System.Web.Mvc;
using WebApplication27.Models.Infrastructure;

namespace WebApplication27.Controllers
{
    [CustomAuthenticationFilter]
    [CustomAuthorize("Manage Reference")]
    public class ReferencesController : Controller
    {
        // GET: References
        private DB_Model db = new DB_Model();

        public ActionResult Index(int? page, string name, string Filter_Value)
        {

                const int pagesize = 5;//number of items per each page
                int pagenum = (page ?? 1); //defult page
                if (name != null)
                {
                    page = 1;
                }
                else
                {
                    name = Filter_Value;// to filter the list by name across all pages ... not only the first page

                }
                ViewBag.FilterValue = name;

            List<REFERENCE> data = db.REFERENCES.OrderBy(q => q.REFERENCE_NAME).OrderBy(r => r.REFERENCE_NAME).ToList();

            if (!String.IsNullOrEmpty(name) && name.Length <= 200)
            {

                 data = data.Where(m => m.REFERENCE_NAME.ToLower().Contains(name.ToLower())).ToList();  //filter by the name


            }
            return View(data.ToPagedList(pagenum, pagesize)); //list to all references ...ordred by name

            



        }

        [HttpGet]
        public ActionResult Create()
        {

            return View();

        }

        [HttpPost]
        public ActionResult Save(referencesModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //insert new references
                    REFERENCE refrence = new REFERENCE();
                    refrence.REFERENCE_NAME = model.REFERENCE_NAME;
                    refrence.VISIBILIT_STATUS = model.VISIBILIT_STATUS;
                    refrence.DISPLAY_ORDER = model.DISPLAY_ORDER;
                    refrence.CREATED_DATE = DateTime.Now;
                    refrence.CREATED_BY = Convert.ToDecimal(User.Identity.Name);
                    db.REFERENCES.Add(refrence);
                    db.SaveChanges();
                    TempData["Success"] = refrence.REFERENCE_NAME + " has been saved successfully";//display a message to inform that (The reference is added successfully)

                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Create", model);//if model is not valid  //we return the page with all validation messages


                }
            }
            catch (Exception ex) when (ex.InnerException.InnerException.Message.Contains("ORA-00001"))
            {
                    TempData["Danger"] = "Reference is already exists";
                    return RedirectToAction("Index");
            }
            catch (Exception )
            {
               TempData["Danger"] = "Sorry, something went wrong";
                return RedirectToAction("Index");
            }
            

        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
      
            REFERENCE model = db.REFERENCES.Where(Models => Models.REFERENCE_ID == id).FirstOrDefault(); //get all related data to the current references Id  

            if(model != null)
            {
                string check = CheckRefrenceId(id);

                switch (check)
                {
                    case "Used In Completed Case":

                        return View("EditUsed", _getRefrence(id));

                    case "Used In Pending Case":

                        TempData["Danger"] = "You cannot edit this reference since it has been used in pending case";
                        return RedirectToAction("Index");

                    case "Not Used at all in any case":

                        return View("Edit", _getRefrence(id));

                    default:

                        return RedirectToAction("Index");
                }
            }
      

                 return RedirectToAction("Index", "Error");


        }


        [HttpPost]
        public ActionResult editReferences(referencesModel model)
        {
            try 
            { 
            REFERENCE data = db.REFERENCES.FirstOrDefault(Models => Models.REFERENCE_ID == model.REFERENCE_ID); //get all related data to the current reference Id  

                if(data != null)
                {
                    if (ModelState.IsValid)
                    {
                        //update
                        data.REFERENCE_NAME = model.REFERENCE_NAME;
                        data.VISIBILIT_STATUS = model.VISIBILIT_STATUS;
                        data.DISPLAY_ORDER = model.DISPLAY_ORDER;
                        data.CHANGED_DATE = DateTime.Now;
                        data.CREATED_BY = Convert.ToDecimal(User.Identity.Name);
                        db.SaveChanges();
                        TempData["Success"] = "The changes are saved successfully"; //display a message to inform that  (changes are saved successfully)
                        return RedirectToAction("Index");

                    }
                    else
                    {
                        //if model is not valid 
                        //we return the page with all validation messages
                        return View("Edit", model);
                    }
                }
                return RedirectToAction("Index", "Error");

            }
            catch (Exception ex) when (ex.InnerException.InnerException.Message.Contains("ORA-00001"))
            {
   
                    TempData["Danger"] = "Reference is already exists";
                    return RedirectToAction("Index");
            }
            catch (Exception)
            {
                    TempData["Danger"] = "Sorry, something went wrong";
                    return RedirectToAction("Index");
            }
        }
 
        [HttpPost]
        public ActionResult editUsedReferences(referencesModel model)
        {
            try 
            { 

            //get all related data to the current references Id  
            REFERENCE data = db.REFERENCES.FirstOrDefault(Models => Models.REFERENCE_ID == model.REFERENCE_ID);


            if (ModelState.IsValid && CheckRefrenceId(model.REFERENCE_ID) == "Used In Completed Case")
            {
                //update status
                data.VISIBILIT_STATUS = model.VISIBILIT_STATUS;
                data.CHANGED_DATE = DateTime.Now;
                data.CREATED_BY = Convert.ToDecimal(User.Identity.Name);
                db.SaveChanges();

                //display a message to inform that  (changes are saved successfully)
                TempData["Success"] = "The changes are saved successfully";
                return RedirectToAction("Index");
            }
            else
            {
                //if model is not valid 
                //we return the page with all validation messages
                return View("EditUsed", model);
            }
            }
            catch (Exception)
            {
                TempData["Danger"] = "Sorry, something went wrong";
                return RedirectToAction("Index");
            }


        }

        [HttpGet]
        public ActionResult GetID3(int REFERENCE_ID)
        {
            try
            {

                REFERENCE model = db.REFERENCES.Where(Models => Models.REFERENCE_ID == REFERENCE_ID).SingleOrDefault(); //get all related data to the current reference Id  


            if (model != null && CheckRefrenceId(REFERENCE_ID) == "Not Used at all in any case")
            {
                return PartialView(model);//delete view ==> if the reference Id is "not" used in case references table

            }
        
                    //not allowed to delete
                    return PartialView("DeleteUsed");
            }
            catch (Exception)
            {
                TempData["Danger"] = "Sorry, something went wrong";
                return RedirectToAction("Index");
            }

        }
 
        [HttpPost]
        public ActionResult deleteref(int REFERENCE_ID)
        {
            try
            {
                //get current reference Id  --> to delete it
                REFERENCE model = db.REFERENCES.Where(Models => Models.REFERENCE_ID == REFERENCE_ID).SingleOrDefault();

                if (CheckRefrenceId(REFERENCE_ID) == "Not Used at all in any case" && model !=null)
                {
                    //delete
                    db.REFERENCES.Remove(model);
                    db.SaveChanges();
                    TempData["Success"] = "Reference deleted successfully";//display a message to inform that (The reference is deleted successfully)
                    return RedirectToAction("Index");
                }


                return RedirectToAction("Index");

            }
            catch (Exception ex) when (ex.InnerException.InnerException.Message.Contains("ORA-02292"))
            {
                TempData["Danger"] = "You cannot delete this reference, since it has been used before";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["Danger"] = "Sorry, something went wrong";
                return RedirectToAction("Index");

            }
            }

        public string CheckRefrenceId(decimal referencesId)
        {

            //check if used in case references table to update all data OR to update the status only
            var check = db.CASE_REFERENCES.Where(x => x.REFERENCE_ID == referencesId).FirstOrDefault();

            //check if used in case references and the case still pending
            var Result = from b in db.CASE_REFERENCES
                         from c in db.CASES

WebApplication27/Views/References/Create.cshtml
@{
    ViewBag.Title = "Create";
}

@model WebApplication27.Models.referencesModel
<div class="d-flex justify-content-center" style="margin:5rem; ">

    <div class="card w-75">
        <div class="card-body">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Add Reference</legend>
                <form method="post" action="@Url.Action("Save", "References")">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <label>Reference Name</label><span class="text-danger">  *</span><br />
                        @Html.TextBoxFor(Models => Models.REFERENCE_NAME, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.REFERENCE_NAME, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label>Status</label><span class="text-danger">  *</span><br />
                        @Html.RadioButtonFor(Models => Models.VISIBILIT_STATUS, "Visible", new { required = "required", name = "Status" }) Visible<br />
                        @Html.RadioButtonFor(Models => Models.VISIBILIT_STATUS, "Hide", new { required = "required", name = "Status" }) Hide
                        @Html.ValidationMessageFor(m => m.VISIBILIT_STATUS, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <lable>Display Order</lable><span class="text-danger">  *</span><br />
                        @Html.TextBoxFor(Models => Models.DISPLAY_ORDER, new { @class = "form-control", required = "required", onkeypress = "return validateNumber(event)" })
                        @Html.ValidationMessageFor(m => m.DISPLAY_ORDER, "", new { @class = "text-danger" })
                    </div>

                    <button type="submit" style="background-color: #428bca; color: #fff" class="btn">Save </button>


                </form>
            </fieldset>
        </div>
    </div>
</div>

WebApplication27/Views/References/DeleteUsed.cshtml
<div>


    <div class="form-horizontal">

        <div class="form-group">

            <div class="col-md-10">
                <p>You cannot delete this reference since it has been used before</p>

            </div>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

        </div>
    </div>

   


</div>

WebApplication27/Views/References/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

@model WebApplication27.Models.referencesModel
<div class="d-flex justify-content-center" style="margin:5rem; ">

    <div class="card w-75">
        <div class="card-body">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Edit Reference</legend>

                @using (Html.BeginForm("editReferences", "References", FormMethod.Post))
                {
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.REFERENCE_ID)
                    @Html.ValidationMessageFor(m => m.REFERENCE_ID, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <label>Reference Name</label><span class="text-danger">  *</span><br />
                        @Html.TextBoxFor(Models => Models.REFERENCE_NAME, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.REFERENCE_NAME, "", new { @class = "text-danger" })



                    </div>
                    <div class="form-group">
                        <label>Status</label><span class="text-danger">  *</span><br />
                        @Html.RadioButtonFor(Models => Models.VISIBILIT_STATUS, "Visible", new { required = "required", name = "Status" }) Visible<br />
                        @Html.RadioButtonFor(Models => Models.VISIBILIT_STATUS, "Hide", new { required = "required", name = "Status" }) Hide
                        @Html.ValidationMessageFor(m => m.VISIBILIT_STATUS, "", new { @class = "text-danger" })

                    </div>
                    <div class="form-group">
                        <lable>Display Order</lable><span class="text-danger">  *</span><br />
                        @Html.TextBoxFor(Models => Models.DISPLAY_ORDER, new { @class = "form-control", required = "required", onkeypress = "return validateNumber(event)" })
                        @Html.ValidationMessageFor(m => m.DISPLAY_ORDER, "", new { @class = "text-danger" })

                    </div>

                    <button type="submit" style="background-color: #428bca; color: #fff" class="btn">Save Changes</button>
                }

            </fieldset>

        </div>

    </div>
</div>

WebApplication27/Views/References/EditUsed.cshtml
@model WebApplication27.Models.referencesModel


@{
    ViewBag.Title = "Edit";
}
<div class="d-flex justify-content-center" style="margin:5rem; ">

    <div class="card w-75">
        <div class="card-body">
            <fieldset class="scheduler-border">
                <legend class="scheduler-border">Edit Reference</legend>

                @using (Html.BeginForm("editUsedReferences", "References", FormMethod.Post))
                {

                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.REFERENCE_ID)
                    @Html.ValidationMessageFor(m => m.REFERENCE_ID, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <label>Reference Name :</label><br />
                        @Html.DisplayFor(Models => Models.REFERENCE_NAME, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.HiddenFor(Models => Models.REFERENCE_NAME)
                        @Html.ValidationMessageFor(m => m.REFERENCE_NAME, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <label> Status</label><span class="text-danger">  *</span><br />
                        @Html.RadioButtonFor(Models => Models.VISIBILIT_STATUS, "Visible", new { required = "required", name = "Status" }) Visible<br />
                        @Html.RadioButtonFor(Models => Models.VISIBILIT_STATUS, "Hide", new { required = "required", name = "Status" }) Hide
                        @Html.ValidationMessageFor(m => m.VISIBILIT_STATUS, "", new { @class = "text-danger" })

                    </div>
                    <div class="form-group">
                        <lable>Display Order :</lable><br />
                        @Html.DisplayFor(Models => Models.DISPLAY_ORDER, new { @class = "form-control", required = "required" })
                        @Html.HiddenFor(Models => Models.DISPLAY_ORDER)
                        @Html.ValidationMessageFor(m => m.DISPLAY_ORDER, "", new { @class = "text-danger" })



                    </div>

                    <button type="submit" style="background-color: #428bca; color: #fff" class="btn">Save</button>
                }

            </fieldset>

        </div>
    </div>
</div>

WebApplication27/Views/References/GetID3.cshtml
@model WebApplication27.Models.REFERENCE


    @using (Html.BeginForm("deleteref", "References", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.REFERENCE_ID)
    <div class="form-horizontal">
        <div class="form-group">

            <div class="col-md-10">
                <p>Are you sure you want to delete @Html.DisplayFor(model => model.REFERENCE_NAME) reference</p>


            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-danger" value="Delete">Delete</button>
        </div>

    </div>
            }

WebApplication27/Views/References/Index.cshtml
@{
    ViewBag.Title = "References";
}
@using PagedList.Mvc

@model PagedList.IPagedList<WebApplication27.Models.REFERENCE>

<h4 style="margin-bottom:20px; margin-top:30px">References</h4>

@*alert messages*@
@if (TempData["Danger"] != null)
{
    <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @TempData["Danger"]
    </div>
}

@if (TempData["Success"] != null)
{
    <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Success!</strong> @TempData["Success"]
    </div>
}

@if (TempData["cannotEdit"] != null)
{
    <div class="success-message">
        <div class="modal fade" id="Model" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">

                <div class="modal-content">
                    <div class="modal-header">
                        <h5>Edit Reference </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p>You cannot edit this reference, since it has been used in pending case</p>
                    </div>
                </div>

            </div>
        </div>
    </div>

}

@*Search Form*@
@using (Html.BeginForm("Index", "References", FormMethod.Get))
{
    <div class="row">
        <div class="col-10">
            <div class="input-group mb-3 w-25">
                @Html.TextBox("name", ViewBag.FilterValue as string, new { @class = "form-control", placeholder = "Name", })

                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Search</button>
                </div>
            </div>
        </div>
        <div class="col-2">
            <a href="@Url.Action("Create", "References")" class="btn" style=" background-color: #428bca; color: #fff;">+ Add Reference</a>
        </div>
    </div>

 

}


@*model for delete reference*@
<div class="modal fade" id="exampleModalLong1" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Delete Reference</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="partial11">



                </div>
            </div>

        </div>
    </div>
</div>


@*Table To read  all reference*@
<table class="table m-1">
    <thead>
        <tr>
            <th>Reference Name </th>
            <th>Status</th>
            <th>Display Order</th>
            <th>Actions</th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {

        <tr id="@item.REFERENCE_ID">
            <td>

                @Html.DisplayFor(modelItem => item.REFERENCE_NAME)
            </td>
            <td>

                @Html.DisplayFor(modelItem => item.VISIBILIT_STATUS)
            </td>
            <td>
                @{

                    var s = item.DISPLAY_ORDER.ToString();

                    @Html.DisplayFor(x => s)


                }
            </td>
            <td>
                <a class="btn btn-link" href="@Url.Action("Edit", "References", new { id = item.REFERENCE_ID })">
                    Edit
                </a>  |
                <input class="vh btn btn-link" type="button" value="Delete"
                       data-assigned-id="@item.REFERENCE_ID" data-toggle="modal" data-target="#exampleModalLong1" />




            </td>


        </tr>



    }


</table>


@*pagination*@

<p>
    @Html.PagedListPager(Model, page => Url.Action("Index", "References",
new
{
    page,
    Filter_Value = ViewBag.FilterValue
}))
</p>

<script type="text/javascript">
    $(document).ready(function () {
        $("#Model").modal();
    });

 $(function () {
   $('.vh').click(function () {
          var REFERENCE_ID = $(this).data('assigned-id');
          var route = '@Url.Action("GetID3", "References")?REFERENCE_ID=' + REFERENCE_ID;
          $('#partial11').load(route);
                });
                });

</script>