WebApplication27/Models/CASE_QUESTIONS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASE_QUESTIONS
    {
        public decimal CASE_ID { get; set; }
        public decimal QUESTION_ID { get; set; }
        public string QUESTION_NAME { get; set; }
        public string ANSWER { get; set; }
        public Nullable<decimal> CHOICE_ID { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual MULTIPLE_CHOICE MULTIPLE_CHOICE { get; set; }
        public virtual QUESTION QUESTION { get; set; }
    }
}

WebApplication27/Models/Case.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication27.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public Case()
        {
            this.CASE_CATEGORIES = new HashSet<CASE_CATEGORIES>();
            this.CASE_COMORBIDITY = new HashSet<CASE_COMORBIDITY>();
            this.CASE_REFERENCES = new HashSet<CASE_REFERENCES>();
            this.CASE_QUESTIONS = new HashSet<CASE_QUESTIONS>();
        }
    
        public decimal CASE_ID { get; set; }
        public System.DateTime CASE_START_DATE { get; set; }
        public string CASE_DESCRIBTION { get; set; }
        public decimal REQUESTER_ID { get; set; }
        public string CASE_TYPE { get; set; }
        public string MRN { get; set; }
        public string NAME { get; set; }
        public string AGE { get; set; }
        public string GENDER { get; set; }
        public string PREGNANT_OR_NOT { get; set; }
        public string PREGNANT_WEEK { get; set; }
        public string ALLERGY_HISTORY { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public string DIAGNOSIS { get; set; }
        public string ELECTROLYTES { get; set; }
        public string LIVER_FUNCTION { get; set; }
        public string LABORATORY_RESULT { get; set; }
        public string SERUM_CREATININE { get; set; }
        public string MEDICATIONS { get; set; }
        public string RELATED_SINGS { get; set; }
        public string HAS_MRN_OR_NOT { get; set; }
        public string URGENCY { get; set; }
        public string ANSWER { get; set; }
        public string RESEARCHER_NAME { get; set; }
        public string ANSWER_GIVEN { get; set; }
        public string NOT_REACHABLE_COMMENT { get; set; }
        public Nullable<decimal> RECEIVER_ID { get; set; }
        public string RECEIVER_NAME { get; set; }
        public string CONTACT_ATTEMPT { get; set; }
        public string CASE_STATUS { get; set; }
        public string IS_DIFFER { get; set; }
        public Nullable<System.DateTime> CASE_END_DATE { get; set; }
        public Nullable<decimal> TIME_SPAN_DAY { get; set; }
        public Nullable<decimal> TIME_SPAN_MINUTES { get; set; }
        public Nullable<decimal> TIME_SPAN_HOUR { get; set; }
        public string CURRENT_STAGE { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public string ULTIMATE_QUESTION { get; set; }
        public string ULTIMATE_CATEGORY { get; set; }
    
        public virtual ICollection<CASE_CATEGORIES> CASE_CATEGORIES { get; set; }
        public virtual ICollection<CASE_COMORBIDITY> CASE_COMORBIDITY { get; set; }
        public virtual ICollection<CASE_REFERENCES> CASE_REFERENCES { get; set; }
        public virtual USER USER { get; set; }
        public virtual REQUESTER REQUESTER { get; set; }
        public virtual ICollection<CASE_QUESTIONS> CASE_QUESTIONS { get; set; }
    }
}

WebApplication27/Models/CheckBox View Models/CaseViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication27.Models
{
    public class CaseViewModel
    {

        [Required(ErrorMessage = "Id is required")]
        public decimal CASE_ID { get; set; }


        public string CASE_TYPE { get; set; }

        public List<categories_> CategoryList { get; set; }

        public List<questions_> QuestionsList { get; set; }

        public List<Case> userCases { get; set; }

        public List<REQUESTER> RequesterList { get; set; }

        public List<PERMISSION> PermissionList { get; set; }

        public IEnumerable<Case> Cases { get; set; }


    }
}

WebApplication27/Controllers/CaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebApplication27.Models;
using PagedList;
using System.Data;
using System.Globalization;
using ClosedXML.Excel;
using System.IO;
using WebApplication27.Models.Infrastructure;

namespace WebApplication27.Controllers
{
    [CustomAuthenticationFilter]
    [CustomAuthorize("Create New Case")]

    public class CaseController : Controller
    {
        // Case
        private DB_Model db = new DB_Model();

        public ActionResult Index()
        {
            //requesters list to bind it in the view 
            List<REQUESTER> list = db.REQUESTERS.ToList();
            ViewBag.Requester = new SelectList(list, "REQUESTER_ID", "REQUESTER_NAME");
            return View();
        }

        [HttpPost]
        public ActionResult saveFirstStage(caseDescriptionStage model)
        {
            try
            {
                if (ModelState.IsValid)
                {


                    String now = DateTime.Now.ToString("MM/dd/yyyy HH:mm");//datetime format
                    DateTime dt = DateTime.Parse(now, new CultureInfo("en-CA"));
                    Case data = new Case();// get data from model
                    data.CASE_START_DATE = dt;
                    data.REQUESTER_ID = model.REQUESTER_ID;
                    data.CASE_DESCRIBTION = model.CASE_DESCRIBTION;
                    data.CASE_TYPE = model.CASE_TYPE;
                    data.CASE_STATUS = "Pending";
                    data.USER_ID = Convert.ToDecimal(User.Identity.Name);
                    data.CURRENT_STAGE = "Description stage";
                    data.URGENCY = model.URGENCY;
                    data.CASE_END_DATE = DateTime.Now;
                    db.CASES.Add(data); //insert the data
                    db.SaveChanges();
                    decimal id = data.CASE_ID;// get crrunt user id  
                    string CaseType = data.CASE_TYPE; // get case type

                    if (CaseType == "General Questions")
                    {

                        return RedirectToAction("getListCategories", new { id });  //if case with general type //we go to the categories stage
                    }

                    return RedirectToAction("getPatientInformation", new { id }); //if case with spesific type // we go to patient information stage
                }
                else
                {

                    List<REQUESTER> list = db.REQUESTERS.ToList();
                    ViewBag.Requester = new SelectList(list, "REQUESTER_ID", "REQUESTER_NAME");//requesters list to bind it in the view 
                    return View("Index", model);//if model is not valid  //we return the view with all validation messages


                }
            }
            catch (Exception)
            {
                TempData["Danger"] = "Sorry, something went wrong";
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult getCaseDescription(decimal id)
        {
            //get all related data to the current case's Id 
            //to check case is pending 
            Case model = db.CASES.Where(Models => Models.CASE_ID == id).Where(models => models.CASE_STATUS == "Pending" || models.CASE_STATUS == "Pending for Approval").SingleOrDefault();

            //requester list to bind it in the view 
            List<REQUESTER> list = db.REQUESTERS.ToList();
            ViewBag.Requester = new SelectList(list, "REQUESTER_ID", "REQUESTER_NAME");
            if (model != null)
            {
                caseDescriptionStage data = new caseDescriptionStage();
                data.CASE_ID = model.CASE_ID;
                data.REQUESTER_ID = model.REQUESTER_ID;
                data.CASE_DESCRIBTION = model.CASE_DESCRIBTION;
                data.CASE_TYPE = model.CASE_TYPE;
                data.URGENCY = model.URGENCY;
                data.CASE_TYPE = model.CASE_TYPE;

                return View(data);
            }

            return View();


        }

        [HttpPost]
        public ActionResult updateCaseDescription(caseDescriptionStage model)
        {
            try
            {
                decimal id = model.CASE_ID;

                if (ModelState.IsValid)
                {

                    Case data = db.CASES.Where(Models => Models.CASE_ID == id).SingleOrDefault();
                    if (data != null)
                    {
                        data.REQUESTER_ID = model.REQUESTER_ID;
                        data.CASE_DESCRIBTION = model.CASE_DESCRIBTION;
                        data.CASE_TYPE = model.CASE_TYPE;
                        data.CASE_STATUS = "Pending";
                        data.USER_ID = Convert.ToDecimal(User.Identity.Name);
                        data.CURRENT_STAGE = "Description stage";
                        data.URGENCY = model.URGENCY;
                        data.CASE_END_DATE = DateTime.Now;

                        db.SaveChanges(); //save data
                        string CaseType = data.CASE_TYPE;

                        if (CaseType == "General Questions")
                        {
                            //go to categories stage
                            return RedirectToAction("getListCategories", new { id });
                        }

                        //go to patient information stage
                        return RedirectToAction("getPatientInformation", new { id });
                    }
                    return RedirectToAction("Index", "Error");


                }
                else
                {

                    List<REQUESTER> list = db.REQUESTERS.ToList();
                    ViewBag.Requester = new SelectList(list, "REQUESTER_ID", "REQUESTER_NAME"); //requester list to bind it in the view 

                    return View("getCaseDescription", model);//if model is not valid //we return the view with all validation messages

                }
            }
            catch (Exception)
            {
                TempData["Danger"] = "Sorry, something went wrong";
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult getPatientInformation(decimal id)
        {

            Case model = db.CASES.Where(Models => Models.CASE_ID == id).Where(models => models.CASE_STATUS == "Pending" || models.CASE_STATUS == "Pending for Approval").SingleOrDefault();

            if (model != null)
            {
                //get patient Information
                patientInformationStage data = new patientInformationStage();
                data.CASE_ID = model.CASE_ID;
                data.patientMRN = model.HAS_MRN_OR_NOT;
                data.MRN = model.MRN;
                data.NAME = model.NAME;
                data.AGE = model.AGE;
                data.GENDER = model.GENDER;
                data.PREGNANT_OR_NOT = model.PREGNANT_OR_NOT;
                data.PREGNANT_WEEK = model.PREGNANT_WEEK;
                data.ALLERGY_HISTORY = model.ALLERGY_HISTORY;
                data.HEIGHT = model.HEIGHT;
                data.WEIGHT = model.WEIGHT;
                data.CASE_START_DATE = model.CASE_START_DATE;
                data.DIAGNOSIS = model.DIAGNOSIS;
                data.ELECTROLYTES = model.ELECTROLYTES;
                data.LIVER_FUNCTION = model.LIVER_FUNCTION;
                data.LABORATORY_RESULT = model.LABORATORY_RESULT;
                data.SERUM_CREATININE = model.SERUM_CREATININE;
                data.MEDICATIONS = model.MEDICATIONS;
                data.RELATED_SINGS = model.RELATED_SINGS;

                //get comorbidities of the case
                var Result = from b in db.COMORBIDITies
                             where (b.VISIBILIT_STATUS == "Visible")
                             orderby (b.DISPLAY_ORDER)
                             select new
                             {
                                 b.COMORBIDITY_ID,
                                 b.COMORBIDITY_NAME,
                                 Checked = ((from ab in db.CASE_COMORBIDITY
                                             where (ab.CASE_ID == id) & (ab.COMORBIDITY_ID == b.COMORBIDITY_ID)
                                             select ab).Count() > 0)//subquery to check if the comorbidity is assigned to the current case's id or not 
                             };

                //make list of comorbidities
                var ComorbidityCheckboxlist = new List<comorbidities_>();

                foreach (var item in Result)
                {

                    string result2 = (from c in db.CASE_COMORBIDITY
                                      where c.CASE_ID == model.CASE_ID && c.OTHER_COMORBIDITY != null
                                      select c.OTHER_COMORBIDITY).FirstOrDefault();//query to get other comorbidity if exists

                    //add every item in result query to the (ComorbidityCheckboxlist)
                    ComorbidityCheckboxlist.Add(new comorbidities_ { id = item.COMORBIDITY_ID, name = item.COMORBIDITY_NAME, Checked = item.Checked, other = result2 });


                }

                data.ComorbidityList = ComorbidityCheckboxlist;
                return View(data);
            }


            return View();

        }

        [HttpPost]
        public ActionResult UpdatePatientInformation(decimal CASE_ID, patientInformationStage model, string SaveAsPending)
        {
            decimal id = model.CASE_ID;

            if (ModelState.IsValid)
            {
                Case data = db.CASES.Where(Models => Models.CASE_ID == CASE_ID).SingleOrDefault();

                if (data != null)
                {
                    //save Patient information
                    data.MRN = model.MRN;
                    data.NAME = model.NAME;
                    data.HAS_MRN_OR_NOT = model.patientMRN;
                    data.AGE = model.AGE;

WebApplication27/Views/Case/Filter.cshtml
@{
    ViewBag.Title = "Cases";
}

@using PagedList.Mvc

@model PagedList.IPagedList<WebApplication27.Models.Case>
<h4 style="margin-bottom:20px; margin-top:30px">Cases</h4>

    @*alert messages*@
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Success!</strong> @TempData["Success"]
        </div>

    }
    @if (TempData["warning"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            @TempData["warning"]
        </div>

    }

    @if (TempData["alert"] != null)
    {
        <div class="alert alert-secondary alert-dismissible fade show">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            @TempData["alert"]
        </div>

    }

    <div class="card">
        <div class="card-body">

            @using (Html.BeginForm("Filter", "Case", FormMethod.Get))
            {

                <div class="form-row">

                    <div class="form-group col-md-2">
                        <label class="mr-sm-2" for="inlineFormCustomSelect">Requester Name</label>
                        @Html.DropDownList("Requestrt_id", ViewBag.ListRequester as SelectList, "", new { @class = "form-control" })

                    </div>
                    <div class="form-group col-md-3">
                        <label class="mr-sm-2" for="inlineFormCustomSelect">From </label>
                        @Html.TextBox("start_date", new { @value = ViewBag.FilterValue3 }, new { @type = "datetime-local", @class = "form-control datepicker" })

                    </div>
                    <div class="form-group col-md-3">
                        <label class="mr-sm-2" for="inlineFormCustomSelect">To </label>
                        @Html.TextBox("End_date", new { @value = ViewBag.FilterValue6 }, new { @type = "datetime-local", @class = "form-control datepicker" })

                    </div>
                    <div class="form-group col-md-2">
                        <label class="mr-sm-2" for="inlineFormCustomSelect">Category Name</label>
                        @Html.DropDownList("Category_id", ViewBag.CategoryList as SelectList, "", new { @class = "form-control" })


                    </div>
                    <div class="form-group col-md-2">
                        <label class="mr-sm-2" for="inlineFormCustomSelect">Name</label>
                        @Html.DropDownList("User_id", ViewBag.userList as SelectList, "", new { @class = "form-control" })


                    </div>
                    <div class="form-group col-md-8">

                        <label class="mr-sm-2" for="inlineFormCustomSelect">Case Status</label>
                        <div class="form-check-inline">
                            @Html.RadioButton("Status", "Pending", new { @value = ViewBag.FilterValue7, @checked = "checked" })
                            <label class="form-check-label" for="exampleRadios1">
                                Pending
                            </label>
                        </div>
                        <div class="form-check-inline">
                            @Html.RadioButton("Status", "Pending for Approval", new { @value = ViewBag.FilterValue7 })
                            <label class="form-check-label" for="exampleRadios2">
                                Pending for Approval
                            </label>
                        </div>
                        <div class="form-check-inline">
                            @Html.RadioButton("Status", "Completed", new { @value = ViewBag.FilterValue7 })
                            <label class="form-check-label" for="exampleRadios3">
                                Completed
                            </label>
                        </div>


                    </div>
                    <div class="form-group col-md-4">
                        <button type="submit" style="background-color: #428bca; color: #fff" class="btn">Apply Filter </button>
                        <button type="submit" name="ExportExcel" id="btn3" class="btn" style="background-color: #428bca; color: #fff">Export to Excel</button>
                        <a href="@Url.Action("Filter", "Case")" class="btn btn-outline-secondary">Reset</a>
                    </div>

                </div>


            }

        </div>
    </div>

    @if (Model != null && Model.Count() != 0)
    {

        @*Table to reading all cases  *@
        <table class="table" style="margin-top:1rem">
            <thead>
                <tr>
                    <th>Case Description </th>
                    <th>
                        Start Date
                    </th>
                    @if (ViewBag.FilterValue7 == "Completed")
                    {
                        <th>End Date </th>
                    }
                    <th>Status</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {

                <tr id="@item.CASE_ID">
                    <td>

                        @{

                            var s = string.Join(" ", item.CASE_DESCRIBTION.Split(' ').Take(5));

                            @Html.DisplayFor(x => s)<span>...</span>


                        }




                    </td>

                    <td>

                        @Html.DisplayFor(modelItem => item.CASE_START_DATE)
                    </td>
                    @if (ViewBag.FilterValue7 == "Completed")
                    {

                        <td>

                            @Html.DisplayFor(modelItem => item.CASE_END_DATE)
                        </td>
                    }
                    <td>

                        @Html.DisplayFor(modelItem => item.CASE_STATUS)
                    </td>
                    <td>

                        @Html.DisplayFor(modelItem => item.USER.FULL_NAME)
                    </td>

                    <td>


                        @if (ViewBag.FilterValue7 == "Completed")
                        {

                            <a href="@Url.Action("CaseDescriptionSatge", "CompletedCases", new { CASE_ID = item.CASE_ID })">
                                View
                            </a>
                        }
                        @if (ViewBag.FilterValue7 == "Pending" || ViewBag.FilterValue7 == "Pending for Approval" || ViewBag.FilterValue7 == null)
                        {


                            <a href="@Url.Action("Edit", "Case", new { id = item.CASE_ID })">
                                Edit
                            </a>
                        }
                    </td>


                </tr>



            }


        </table>

        <p>
            @Html.PagedListPager(Model, Page_No => Url.Action("Filter", "Case",
        new
        {
            Page_No,
            Filter_Value2 = ViewBag.FilterValue2,
            Filter_Value3 = ViewBag.FilterValue3,
            Filter_Value4 = ViewBag.FilterValue4,
            Filter_Value5 = ViewBag.FilterValue5,
            Filter_Value6 = ViewBag.FilterValue6,
            Filter_Value7 = ViewBag.FilterValue7,





        }))
        </p>

    }
    else
    {
        <p>No Case found</p>
    }


<script>
    $(document).ready(function () {
        $("#Model").modal();
    });
</script>

WebApplication27/Views/Case/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@if (Request.IsAuthenticated)
{


    @model WebApplication27.Models.caseDescriptionStage


    <div class="card shadow-sm" style="margin-top:7%">

        <nav>
            <div class="nav nav-pills nav-fill" id="nav-tab" role="tablist">
                <a class="nav-link" id="step1-tab" style="color: #428bca;text-decoration: underline;" data-toggle="tab" href="#step1">Case Description</a>
                <a class="nav-link" id="step2-tab" style=" color:gray" data-toggle="tab" href="#step2">Patient Information</a>
                <a class="nav-link" id="step3-tab" style=" color:gray" data-toggle="tab" href="#step3">Categories</a>
                <a class="nav-link" id="step1-tab" style=" color:gray" href="#step1">Questions</a>
                <a class="nav-link" id="step2-tab" style=" color:gray" href="#step2">Case Details</a>
                <a class="nav-link" id="step3-tab" style=" color:gray" href="#step3">Answer</a>
                <a class="nav-link" id="step2-tab" style=" color:gray" href="#step2">Record</a>
            </div>
        </nav>
        <div class="card-body">
            @using (Html.BeginForm("saveFirstStage", "Case", FormMethod.Post))
            {
                @Html.ValidationSummary(true)
                <div class="tab-content py-4" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="step1">


                        <div class="mb-3">
                            <label>Requester Name</label><span class="text-danger">  *</span><br />
                            @Html.DropDownListFor(Models => Models.REQUESTER_ID, ViewBag.Requester as SelectList, "Select", new { @class = "form-control", required = "required" })
                            @Html.ValidationMessageFor(m => m.REQUESTER_ID, "", new { @class = "text-danger" })
                        </div>
                        <div class="mb-3">
                            <label for="Case_Describtion">Case Description</label><span class="text-danger">  *</span>
                            @Html.TextAreaFor(Models => Models.CASE_DESCRIBTION, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CASE_DESCRIBTION, "", new { @class = "text-danger" })

                        </div>
                        <div class="mb-3">

                            <label class="radio control-label">Case Type  <span class="text-danger">  *</span></label><br />
                            @Html.RadioButtonFor(Models => Models.CASE_TYPE, "Patient Specific Question")Patient Spesific Question<br />
                            @Html.RadioButtonFor(Models => Models.CASE_TYPE, "General Questions")General Question<br />
                            @Html.ValidationMessageFor(model => model.CASE_TYPE, "", new { @class = "text-danger" })

                        </div>
                        <div class="mb-3">
                            <label class="radio control-label">Case Urgency <span class="text-danger">  *</span></label><br />
                            @Html.RadioButtonFor(Models => Models.URGENCY, "Urgent", new { @class = "requireded", name = "Urgency" }) Urgent (On the Same Day)<br />
                            @Html.RadioButtonFor(Models => Models.URGENCY, "Regular", new { @class = "requireded", name = "Urgency" })Regular (Maximium 5 Working Day)<br />
                            @Html.ValidationMessageFor(model => model.URGENCY, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row justify-content-between">
                        <div class="col-auto"></div>

                        <div class="col-auto">
                            <button type="submit" class="btn" style="background-color: #428bca; color: #fff" data-enchanter="next">
                                Save and continue
                            </button>

                        </div>
                    </div>
                </div>

                }
            </div>


    </div>

   



}
else
{

    <div></div>
}

WebApplication27/Views/Case/caseQuestions.cshtml
@{
    ViewBag.Title = "Questions List";
}
@model WebApplication27.Models.CaseViewModel


@using (Html.BeginForm("SaveCaseQuestions", "Case", FormMethod.Post))
{
    if (Model != null)
    {

        <span id="error" class="field-validation-error">
            <span class="text-danger">Select any Questions </span>
        </span>
        @*alert messages*@
        if (TempData["Danger"] != null)
        {
            <div class="alert alert-danger alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                @TempData["Danger"]
            </div>
        }
        <table class="table mt-3">
            <thead>
                <tr>
                    <th>
                        @Html.CheckBox("QuestionCH", new { id = "id-of-checkall-checkbox", name = "QuestionCH" })
                    </th>
                    <th>Question Name</th>
                    <th>Category </th>


                </tr>
            </thead>

            @for (int i = 0; i < Model.QuestionsList.Count(); i++)
            {
                @Html.Raw("<tr>")

                @Html.HiddenFor(m => Model.CASE_ID)
                @Html.Raw("<td>")

                if (Model.QuestionsList[i].defult == "Yes")
                {

                    @Html.DisplayFor(m => Model.QuestionsList[i].Checked, new { @class = "QuestionCH", @checked = true, value = true, @disabled = "disabled" })
                    @Html.CheckBoxFor(m => Model.CategoryList[i].Checked, new { @class = "QuestionCH", value = true, @checked = true, style = "display: none" })

                    @Html.HiddenFor(m => Model.QuestionsList[i].Checked)


                }
                if (Model.QuestionsList[i].defult == "No")
                {

                    @Html.CheckBoxFor(m => Model.QuestionsList[i].Checked, new { @class = "QuestionCH", id = "Category", name = "CategoryCH" })


                }

                @Html.Raw("</td>")




                @Html.Raw("<td>")
                @Html.DisplayFor(m => Model.QuestionsList[i].name)
                @Html.Raw("</td>")
                @Html.Raw("<td>")
                @Html.DisplayFor(m => Model.QuestionsList[i].Category)
                @Html.Raw("</td>")
                @Html.HiddenFor(m => Model.QuestionsList[i].id)
                @Html.HiddenFor(m => Model.QuestionsList[i].name)


                @Html.Raw("</tr>")

            }





        </table>
        <br />
        <br />


        <div class="row justify-content-between">
            <div class="col-auto">
            </div>
            <div class="col-auto">

                <button type="submit" name="save" id="btn2" class="btn" style="background-color: #428bca; color: #fff">
                    Save
                </button>
            </div>
        </div>


    }
    else
    {
        <p>No Data Found</p>
    }



}


@section Scripts {
    <script type="text/javascript">

        var declarationsError = $('#error').hide();
        $('#btn2, #btn3').click(function () {



            if ($(".QuestionCH:checkbox:checked").length > 0) {
                declarationsError.hide();
                return true;
            } else {
                declarationsError.show();
                return false;
            }
        });

        $('.QuestionCH').change(function () {
            if ($(this).is(':checked')) {
                declarationsError.hide(); // hide error message
            }
        });
        //select all
        $("#id-of-checkall-checkbox").click(function () {
            $(".QuestionCH").attr('checked', this.checked);
        });
    </script>
}